-- AlterTable
ALTER TABLE `Formation` ADD COLUMN `statut` ENUM('EN_ATTENTE', 'VALIDEE', 'REJETEE') NOT NULL DEFAULT 'EN_ATTENTE';

-- AlterTable
ALTER TABLE `Professeur` ADD COLUMN `statut` ENUM('EN_ATTENTE', 'VALIDE', 'REJETE') NOT NULL DEFAULT 'EN_ATTENTE';
